/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModularRouteImport } from './routes/modular'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KomparasiRouteImport } from './routes/komparasi'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules.$moduleId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularRoute = ModularRouteImport.update({
  id: '/modular',
  path: '/modular',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KomparasiRoute = KomparasiRouteImport.update({
  id: '/komparasi',
  path: '/komparasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/komparasi': typeof KomparasiRoute
  '/login': typeof LoginRoute
  '/modular': typeof ModularRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/komparasi': typeof KomparasiRoute
  '/login': typeof LoginRoute
  '/modular': typeof ModularRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/komparasi': typeof KomparasiRoute
  '/login': typeof LoginRoute
  '/modular': typeof ModularRoute
  '/onboarding': typeof OnboardingRoute
  '/payment': typeof PaymentRoute
  '/register': typeof RegisterRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/komparasi'
    | '/login'
    | '/modular'
    | '/onboarding'
    | '/payment'
    | '/register'
    | '/roadmap'
    | '/settings'
    | '/modules/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/komparasi'
    | '/login'
    | '/modular'
    | '/onboarding'
    | '/payment'
    | '/register'
    | '/roadmap'
    | '/settings'
    | '/modules/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/komparasi'
    | '/login'
    | '/modular'
    | '/onboarding'
    | '/payment'
    | '/register'
    | '/roadmap'
    | '/settings'
    | '/modules/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KomparasiRoute: typeof KomparasiRoute
  LoginRoute: typeof LoginRoute
  ModularRoute: typeof ModularRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentRoute: typeof PaymentRoute
  RegisterRoute: typeof RegisterRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular': {
      id: '/modular'
      path: '/modular'
      fullPath: '/modular'
      preLoaderRoute: typeof ModularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komparasi': {
      id: '/komparasi'
      path: '/komparasi'
      fullPath: '/komparasi'
      preLoaderRoute: typeof KomparasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KomparasiRoute: KomparasiRoute,
  LoginRoute: LoginRoute,
  ModularRoute: ModularRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentRoute: PaymentRoute,
  RegisterRoute: RegisterRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  ModulesModuleIdRoute: ModulesModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
